@startuml
'https://plantuml.com/class-diagram

class ResourceAllocator

class ResourceAllocator {
- {static} INVALID_RESOURCE_ID : int = -1
+ allocate(resourceType : ResourceType) : int
+ free(resourceType : ResourceType, resourceId : int) : void
- markSpaceSlotFree(resourceId : int) : void
- markTimeSlotFree(resourceId : int) : void
- markSpaceSlotBusy(resourceId : int) : void
- markTimeSlotBusy(resourceId : int) : void
- findFreeSpaceSlot() : int
- findFreeTimeSlot() : int
}

enum ResourceType {
TIME_SLOT
SPACE_SLOT
}

@enduml