@startuml
'https://plantuml.com/class-diagram

class CarManager
class Car

class CarManager {
- _carsDb : Car[]
+ getFromDb(carId  : String) : Car
+ getCarsNames(): String
+ getBestCar() : Car
}
class Car {
- _id : String
- _model : String
- _brand : String
+ getId() : String
+ getModel() : String
+ getBrand() : String
}

CarManager o- Car

@enduml