@startuml
'https://plantuml.com/class-diagram

interface Door
interface SensorProvider
interface TimerProvider
class Sensor
class Timer
class SensingDoor
class TimedDoor

interface Door{
lock() : void
unlock() : void
open() : void
close() : void
}

interface SensorProvider{
proximityCallback() : void
}

interface TimerProvider{
timeOutCallback() : void
}

class Sensor{
+ register(sensorProvider : SensorProvider) : void
- isPersonClose() : boolean
}

class Timer{
+ register(timeOut : long, timerProvider : TimerProvider) : void
}

class SensingDoor{
- _locked : boolean
- _opened : boolean
+ lock() : void
+ unlock() : void
+ open() : void
+ close() : void
+ proximityCallback() : void
}

class TimedDoor{
- {static} TIME_OUT : int = 100
- _locked : boolean
- _opened : boolean
+ lock() : void
+ unlock() : void
+ open() : void
+ close() : void
+ timeOutCallback() : void
}

Sensor ..> SensorProvider
Timer ..> TimerProvider

SensingDoor ..|> Door
SensingDoor ..|> SensorProvider
SensingDoor --> Sensor

TimedDoor ..|> Door
TimedDoor ..|> TimerProvider
TimedDoor --> Timer

@enduml